on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: echo 'Hello'
      - run: pwsh -File generate_name.ps1
  job2:
    needs: 
      - job1
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3

